# GitHub Personal Access Token Configuration (Automated Login)
backend:
  name: github
  repo: mail-drafts7/fumadocs_decapcrm_setup
  branch: main
  # No auth_endpoint needed - will use token directly

site_url: http://localhost:3001
display_url: http://localhost:3001

media_folder: public/images
public_folder: /images

collections:
  - name: "docs"
    label: "Documentation"
    folder: "content/docs"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Order", name: "order", widget: "number", required: false }

editor:
  preview: true
